name: testdeptech
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.7.0
  firebase_auth: 4.2.9
  cloud_firestore: 4.4.3
  firebase_storage: 11.0.14
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  uuid: ^3.0.7
  intl: 0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
